# registers, components, rom, ram, io, word size, component definitions, register definitions, instruction set

# General
cpu_name: "Simple CPU"
cpu_version: "1.0"
cpu_description: "A simple CPU with 16 registers, 16-bit word size, and 16-bit address space."
creator: "John Doe"

pipelined: True
address_space: 16
word_size: 16
simulation_speed: 0 # 0 if instant, other wise hertz


# flags
flags: # flag: id
  "zero": 0
  "carry": 1
  "overflow": 2
  
# pipline
pipeline:
  - "InstructionFetch"
  - "InstructionDecode"
  - "Execute"
  - "MemoryAccess"
  - "Writeback"



# Registers
register_count: 16
special_registers: # replace the entire category with an empty list if not wanting any special_regs
  - name: "zero_reg"
    description: "Register that always contains 0."
    address: 0
    read_only: True
    write_only: False
    default_value: 0
    size: 16
    accumulates: False

# ROM/RAM
rom_size: 256
ram_size: 256

# IO
io_type: "mmio" # pmio or mmio
io_reserved: [0,1] # only if mmio
io_ports:
  - name: "io_port_1"
    description: "Port 1 for IO."
    address: 0
    size: 16
    read_only: False
    write_only: False
    default_value: 0
  - name: "io_port_2"
    description: "Port 2 for IO."
    address: 1
    size: 16
    read_only: False
    write_only: False
    default_value: 0

# Components
components:
  - class: "ALU"
    output:
      - "data1"
    forwarder: True
    forwarded_operands:
      - "src1"
      - "src2"
    forward_depth: 2
    operations_handled:
      - "add"
      - "sub"
      - "and"
      - "or"
      - "xor"
  - class: "PC"
    output: []
    forwarder: False
    forwarded_instructions: []
    operations_handled:
      - "Jmp"
  - class: "RAM"
    output: []
    forwarder: False
    description: "Random Access Memory. Pointers"
    operations_handled:
      - "write"
  - class: "Registers"
    output: []
    forwarded_instructions: []
    forwarder: False
    operations_handled:
      - "Lod"
      - "Write"
    
# operation latency removed from here as it was handled  in instruction set

# Instruction Set | Different for pipelined and not pipelined
opcode_length: 16
instruction_set:
  - name: "ADD"
    opcode: 0
    # for the operations pipeline it looks likes work to write but it will be generated by a easier GUI later
    # tho for now we write isntructions the boring way
    # put "None for operations where it is blank or does something like fetches and decodes. Not important for proc"
    operation:
       InstructionFetch: "None"
       InstructionDecode: "REGISTERS.READ"
       Execute: "ALU.ADD"
       MemoryAccess: "None"
       Writeback: "Registers.WRITE" # add this function

    description: "Add two registers."
    operands: # operands are in order of appearance
      - name: "dest"
        type: "register"
        size: 16
      - name: "src1"
        type: "register"
        size: 16
      - name: "src2"
        type: "register"
        size: 16
    latency: 1
    flags_affected:
      - "zero"
      - "carry"
      - "overflow"
  - name: "LDI"
    opcode: 1
    # for the operations pipeline it looks likes work to write but it will be generated by a easier GUI later
    # tho for now we write isntructions the boring way
    # put "None for operations where it is blank or does something like fetches and decodes. Not important for proc"
    operation:
       InstructionFetch: "None"
       InstructionDecode: "None"
       Execute: "None"
       MemoryAccess: "None"
       Writeback: "Registers.LDI" # add this function

    description: "Add two registers."
    operands: # operands are in order of appearance
      - name: "dest"
        type: "register"
        size: 16
      - name: "imm"
        type: "immediate"
        size: 16
    latency: 1
    flags_affected: []
  - name: "HLT"
    opcode: 2
    # for the operations pipeline it looks likes work to write but it will be generated by a easier GUI later
    # tho for now we write isntructions the boring way
    # put "None for operations where it is blank or does something like fetches and decodes. Not important for proc"
    operation:
       InstructionFetch: "None"
       InstructionDecode: "None"
       Execute: "None"
       MemoryAccess: "None"
       Writeback: "CLOCK.HLT" # add this function

    description: "Halts Program"
    operands: [] # operands are in order of appearancediate"
    latency: 1
    flags_affected: []
